### ISSUE TITLE
update the ymal build files for both merge and pr

### ISSUE THREAD

**Issue by brockgilman** [brockgilman/SummarAIze#8]
workflow for pr yaml file, which works:
```
# This file was auto-generated by the Firebase CLI
# https://github.com/firebase/firebase-tools

name: Deploy to Firebase Hosting on PR
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm ci
          npm run build
        working-directory: ./frontend
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SUMMARAIZE_8487F }}
          projectId: summaraize-8487f
```

update merge yaml file accordingly, should be easy, i'll take care tomorrow.

(honestly a reminder for myself to change this)
